baseURL: "https://examplesite.com/"
title: Tech Blogs By Bhushan
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Tech Blogs By Bhushan
  description: "Tech Blogs By Bhushan"
  keywords: [Blog, Tech]
  author: Bhushan Sonawane
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto 
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Tech Blogs By Bhushan"
    icon: /apple-touch-icon.png
    iconHeight: 45

  homeInfoParams:
    Title: "Hi there It's Bhushan \U0001F44B"
    Content: Welcome to my blog site. Here I post blogs about various tech related topics

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: github
      url: "https://github.com/sonawane-bhushan"

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false